"""Fix duplicate user_id column

Revision ID: c88b6ece3e8c
Revises: 606e139165bb
Create Date: 2025-01-19 16:19:06.312015

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c88b6ece3e8c'
down_revision = '606e139165bb'
branch_labels = None
depends_on = None


def upgrade():
    # debt tablosunu oluştur
    op.create_table(
        'debt',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('debtor_id', sa.Integer, nullable=False),
        sa.Column('amount', sa.Float, nullable=False),
        sa.Column('due_date', sa.Date, nullable=False),
        sa.Column('date', sa.DateTime, nullable=True),
        sa.Column('user_id', sa.Integer, nullable=False),  # user_id sütunu eklendi
        sa.ForeignKeyConstraint(['debtor_id'], ['debtor.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'])  # user_id yabancı anahtarı eklendi
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt')  # debt tablosunu geri al
    # ### end Alembic commands ###